/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface FTSOManagerMockInterface extends ethers.utils.Interface {
  functions: {
    "addRewardEpoch(uint256,uint256,uint256)": FunctionFragment;
    "getCurrentRewardEpoch()": FunctionFragment;
    "getRewardEpochVotePowerBlock(uint256)": FunctionFragment;
    "rewardEpochs(uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "addRewardEpoch",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentRewardEpoch",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRewardEpochVotePowerBlock",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "rewardEpochs",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "addRewardEpoch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentRewardEpoch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRewardEpochVotePowerBlock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rewardEpochs",
    data: BytesLike
  ): Result;

  events: {};
}

export class FTSOManagerMock extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: FTSOManagerMockInterface;

  functions: {
    addRewardEpoch(
      _vpBlock: BigNumberish,
      _startBlock: BigNumberish,
      _startTimestamp: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getCurrentRewardEpoch(overrides?: CallOverrides): Promise<[BigNumber]>;

    getRewardEpochVotePowerBlock(
      _rewardEpoch: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    rewardEpochs(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        votepowerBlock: BigNumber;
        startBlock: BigNumber;
        startTimestamp: BigNumber;
      }
    >;
  };

  addRewardEpoch(
    _vpBlock: BigNumberish,
    _startBlock: BigNumberish,
    _startTimestamp: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getCurrentRewardEpoch(overrides?: CallOverrides): Promise<BigNumber>;

  getRewardEpochVotePowerBlock(
    _rewardEpoch: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  rewardEpochs(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber] & {
      votepowerBlock: BigNumber;
      startBlock: BigNumber;
      startTimestamp: BigNumber;
    }
  >;

  callStatic: {
    addRewardEpoch(
      _vpBlock: BigNumberish,
      _startBlock: BigNumberish,
      _startTimestamp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    getCurrentRewardEpoch(overrides?: CallOverrides): Promise<BigNumber>;

    getRewardEpochVotePowerBlock(
      _rewardEpoch: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    rewardEpochs(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        votepowerBlock: BigNumber;
        startBlock: BigNumber;
        startTimestamp: BigNumber;
      }
    >;
  };

  filters: {};

  estimateGas: {
    addRewardEpoch(
      _vpBlock: BigNumberish,
      _startBlock: BigNumberish,
      _startTimestamp: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getCurrentRewardEpoch(overrides?: CallOverrides): Promise<BigNumber>;

    getRewardEpochVotePowerBlock(
      _rewardEpoch: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    rewardEpochs(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addRewardEpoch(
      _vpBlock: BigNumberish,
      _startBlock: BigNumberish,
      _startTimestamp: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getCurrentRewardEpoch(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getRewardEpochVotePowerBlock(
      _rewardEpoch: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    rewardEpochs(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
