/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface NFTClaimTrackerV5Interface extends ethers.utils.Interface {
  functions: {
    "claimNFT(uint256,address)": FunctionFragment;
    "claimableNFTs(uint256)": FunctionFragment;
    "getRequirements(uint256)": FunctionFragment;
    "getVaultWalletAddress(uint256)": FunctionFragment;
    "getVotePowerByAddressBlock(address,uint256)": FunctionFragment;
    "hasNotClaimed(address,uint256)": FunctionFragment;
    "initialize(address,address,address)": FunctionFragment;
    "meetsRequirements(address,uint256)": FunctionFragment;
    "owner()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "tokenClaimed(address,uint256)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "tsoAddress()": FunctionFragment;
    "userIsEligible(address,uint256)": FunctionFragment;
    "votePowerAddress()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "claimNFT",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "claimableNFTs",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRequirements",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getVaultWalletAddress",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getVotePowerByAddressBlock",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasNotClaimed",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "meetsRequirements",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "tokenClaimed",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "tsoAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "userIsEligible",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "votePowerAddress",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "claimNFT", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimableNFTs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRequirements",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVaultWalletAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVotePowerByAddressBlock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasNotClaimed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "meetsRequirements",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokenClaimed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tsoAddress", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "userIsEligible",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "votePowerAddress",
    data: BytesLike
  ): Result;

  events: {
    "ClaimableNFTAdded(uint256,address,uint256,tuple[])": EventFragment;
    "ClaimableNFTUpdated(uint256,address,uint256,tuple[])": EventFragment;
    "NFTClaimed(uint256,address)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ClaimableNFTAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ClaimableNFTUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NFTClaimed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
}

export class NFTClaimTrackerV5 extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: NFTClaimTrackerV5Interface;

  functions: {
    claimNFT(
      _idToClaim: BigNumberish,
      _transferFrom: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    claimableNFTs(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, string, BigNumber] & {
        vaultWallet: string;
        claimableContract: string;
        tokenId: BigNumber;
      }
    >;

    getRequirements(
      _idToClaim: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        ([BigNumber, BigNumber] & {
          blockToCheck: BigNumber;
          votePowerNeeded: BigNumber;
        })[]
      ] & {
        requirements: ([BigNumber, BigNumber] & {
          blockToCheck: BigNumber;
          votePowerNeeded: BigNumber;
        })[];
      }
    >;

    getVaultWalletAddress(
      _idToClaim: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getVotePowerByAddressBlock(
      _addressToCheck: string,
      _blockToCheck: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    hasNotClaimed(
      _addressToCheck: string,
      _idToClaim: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    initialize(
      _tsoAddress: string,
      _votePowerAddress: string,
      _contractAdmin: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    meetsRequirements(
      _addressToCheck: string,
      _idToClaim: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    tokenClaimed(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    tsoAddress(overrides?: CallOverrides): Promise<[string]>;

    userIsEligible(
      _addressToCheck: string,
      _idToClaim: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    votePowerAddress(overrides?: CallOverrides): Promise<[string]>;
  };

  claimNFT(
    _idToClaim: BigNumberish,
    _transferFrom: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  claimableNFTs(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [string, string, BigNumber] & {
      vaultWallet: string;
      claimableContract: string;
      tokenId: BigNumber;
    }
  >;

  getRequirements(
    _idToClaim: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    ([BigNumber, BigNumber] & {
      blockToCheck: BigNumber;
      votePowerNeeded: BigNumber;
    })[]
  >;

  getVaultWalletAddress(
    _idToClaim: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  getVotePowerByAddressBlock(
    _addressToCheck: string,
    _blockToCheck: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  hasNotClaimed(
    _addressToCheck: string,
    _idToClaim: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  initialize(
    _tsoAddress: string,
    _votePowerAddress: string,
    _contractAdmin: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  meetsRequirements(
    _addressToCheck: string,
    _idToClaim: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  owner(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  tokenClaimed(
    arg0: string,
    arg1: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  tsoAddress(overrides?: CallOverrides): Promise<string>;

  userIsEligible(
    _addressToCheck: string,
    _idToClaim: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  votePowerAddress(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    claimNFT(
      _idToClaim: BigNumberish,
      _transferFrom: string,
      overrides?: CallOverrides
    ): Promise<void>;

    claimableNFTs(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, string, BigNumber] & {
        vaultWallet: string;
        claimableContract: string;
        tokenId: BigNumber;
      }
    >;

    getRequirements(
      _idToClaim: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      ([BigNumber, BigNumber] & {
        blockToCheck: BigNumber;
        votePowerNeeded: BigNumber;
      })[]
    >;

    getVaultWalletAddress(
      _idToClaim: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    getVotePowerByAddressBlock(
      _addressToCheck: string,
      _blockToCheck: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    hasNotClaimed(
      _addressToCheck: string,
      _idToClaim: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    initialize(
      _tsoAddress: string,
      _votePowerAddress: string,
      _contractAdmin: string,
      overrides?: CallOverrides
    ): Promise<void>;

    meetsRequirements(
      _addressToCheck: string,
      _idToClaim: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    owner(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    tokenClaimed(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    tsoAddress(overrides?: CallOverrides): Promise<string>;

    userIsEligible(
      _addressToCheck: string,
      _idToClaim: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    votePowerAddress(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    ClaimableNFTAdded(
      itemId?: BigNumberish | null,
      claimableContract?: string | null,
      tokenId?: BigNumberish | null,
      requirements?: null
    ): TypedEventFilter<
      [
        BigNumber,
        string,
        BigNumber,
        ([BigNumber, BigNumber] & {
          blockToCheck: BigNumber;
          votePowerNeeded: BigNumber;
        })[]
      ],
      {
        itemId: BigNumber;
        claimableContract: string;
        tokenId: BigNumber;
        requirements: ([BigNumber, BigNumber] & {
          blockToCheck: BigNumber;
          votePowerNeeded: BigNumber;
        })[];
      }
    >;

    ClaimableNFTUpdated(
      itemUpdated?: BigNumberish | null,
      claimableContract?: string | null,
      tokenId?: BigNumberish | null,
      requirements?: null
    ): TypedEventFilter<
      [
        BigNumber,
        string,
        BigNumber,
        ([BigNumber, BigNumber] & {
          blockToCheck: BigNumber;
          votePowerNeeded: BigNumber;
        })[]
      ],
      {
        itemUpdated: BigNumber;
        claimableContract: string;
        tokenId: BigNumber;
        requirements: ([BigNumber, BigNumber] & {
          blockToCheck: BigNumber;
          votePowerNeeded: BigNumber;
        })[];
      }
    >;

    NFTClaimed(
      itemId?: BigNumberish | null,
      claimingAddress?: string | null
    ): TypedEventFilter<
      [BigNumber, string],
      { itemId: BigNumber; claimingAddress: string }
    >;

    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;
  };

  estimateGas: {
    claimNFT(
      _idToClaim: BigNumberish,
      _transferFrom: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    claimableNFTs(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRequirements(
      _idToClaim: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getVaultWalletAddress(
      _idToClaim: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getVotePowerByAddressBlock(
      _addressToCheck: string,
      _blockToCheck: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    hasNotClaimed(
      _addressToCheck: string,
      _idToClaim: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    initialize(
      _tsoAddress: string,
      _votePowerAddress: string,
      _contractAdmin: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    meetsRequirements(
      _addressToCheck: string,
      _idToClaim: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    tokenClaimed(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    tsoAddress(overrides?: CallOverrides): Promise<BigNumber>;

    userIsEligible(
      _addressToCheck: string,
      _idToClaim: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    votePowerAddress(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    claimNFT(
      _idToClaim: BigNumberish,
      _transferFrom: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    claimableNFTs(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getRequirements(
      _idToClaim: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getVaultWalletAddress(
      _idToClaim: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getVotePowerByAddressBlock(
      _addressToCheck: string,
      _blockToCheck: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    hasNotClaimed(
      _addressToCheck: string,
      _idToClaim: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    initialize(
      _tsoAddress: string,
      _votePowerAddress: string,
      _contractAdmin: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    meetsRequirements(
      _addressToCheck: string,
      _idToClaim: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    tokenClaimed(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    tsoAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    userIsEligible(
      _addressToCheck: string,
      _idToClaim: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    votePowerAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
